### ISSUE TITLE
'end' emitted too early

### ISSUE THREAD

**Issue by elmalto** [coolaj86/node-walk#31]
I am trying to have an entire folder with images (>10000) scanned, then save all file paths in a mongodb database for further processing and then, once everything is done, have my callback(null,2) called so my next function can run (it needs the path information). Unfortunately the walker does not wait until the next() calls are called but quite a bit before. 

      var options = {
        listeners: {
          directories: function (root, dirStatsArray, next) {
            dirStatsArray.forEach(function (stat) {
              console.log('Reading folder ' + path.basename(root), stat.name);
            });
            next();
          },
          file: function (root, fileStats, next) {
            if (fileStats.name.match(/(?:jpg|jpeg|cr2|nef|png)/)) {
              var path = root + '/' + fileStats.name;
              image.find({path:path}, function (err,entry) {
                if (err) return console.log(err);
                if (entry.length) {
                  console.log(fileStats.name + ' already in DB');
                  next();
                }
                else {
                  var thisImage = new image(
                    {
                      filename: fileStats.name,
                      root: root,
                      path: path
                    });
                  thisImage.save(function (err,doc) {
                    console.log('File ' + doc.filename + ' saved to DB');
                    next();
                  });
    
                }
              });
    
            }
            else {
              console.log('Skipping ' + fileStats.name);
              next();
            }
          },
          errors: function (root, nodeStatsArray, next) {
            next();
          },
          end: function () {
              console.log('***** Files read into database *****');
              callback(null,2);
          }
        }
      };
    
    walk.walkSync(dir, options);

**Comment by miketeix** [comment]
I'm getting a similar issue. End seems to be fire right away. I tried both the sync and async versions... Could there be something I'm missing?

**Comment by miketeix** [comment]
It turns out I was using ```fs.readFile``` instead of the synchronous  ```fs.readFileSync``` inside my fileHandler function. The 'end' event  was alway firing at the appropriate time, I just couldn't tell with my async code.

**Comment by coolaj86** [comment]
Looks like both of these cases were a matter of misunderstanding async apis. Closing.
