### ISSUE TITLE
Doesn't seem to be working for paths with more than one level of depth

### ISSUE THREAD

**Issue by diasdavid** [coolaj86/node-walk#32]
`var walker = walk.walk('/tmp', options);` works
`var walker = walk.walk('/tmp/anotherFolder', options);` doesn't work

The anotherFolder exists and has stuff on it, if I symlink it so it becomes on `/anotherFolder`, then it works

Am I missing something?

**Comment by windmaomao** [comment]
I actually have the opposite issue, how do I stop just for that level, ex. on('file') gives me all the files recursively, how can i just get the ones on that level. thanks.

**Comment by IonicaBizau** [comment]
I need the same feature like @windmaomao I want to get all the files/dirs from a known depth. /cc @coolaj86

**Comment by coolaj86** [comment]
Just don't call the next callback and it will stop.

Or filter out the dirs you don't want in the 'directories' event.

Or just use fa.readdir to not read anything recursively at all.

**Comment by coolaj86** [comment]
Closing this because... it seems closable.

See discussion at https://github.com/coolaj86/node-walk/issues/49 if you have any further questions.
