### ISSUE TITLE
if you call walk from within a for loop, it won't find any files.

### ISSUE THREAD

**Issue by vwhpwcbf** [coolaj86/node-walk#40]
Exact same code, pointing at exact same directory, but if I wrap it in a for loop, walk all of a sudden stops returning any file results. Just exits immediately. Is there some global state or something that you need to sort out?

**Comment by BT23** [comment]
I think I am having the same problem.

**Comment by coolaj86** [comment]
Have a code example?

If there is any global state, it's an accident.

I would think the code should look something like this:

```javascript
var walk = require('walk');
var fs = require('fs');
var count = 0;

fs.readdir('/someplace', 'function (dirs) {
  dirs.forEach(function () {
    var walker  = walk.walk("/tmp", { followLinks: false });
    walker.on('end', function () {
      count += 1;
      if (dirs.length === count) {
        onComplete();
      }
    });
  });
});
  , walker  = walk.walk("/tmp", { followLinks: false })
  ;
```

**Comment by coolaj86** [comment]
In general, however, I this is not a good thing to run in a loop. I don't know what your use case is, but unless you're walking separate file systems or have a very unique and special case, you should do it in sequence.

**Comment by BT23** [comment]
This is essentially my code. It's the most reliable way that I could think of doing it.
```javascript
var walk = require('walk'),
	walker = walk.walk('/tmp', { followLinks: false});

var repos = [some git repos to clone]

function clone(callback) {
	var cycle = 0;
	for (var i = 0; i < repos.length; i++) {
		cloneGitRepo(repos[i], '/tmp', function() {
				cycle++;
				//if it's the last time the loop is being run...
				if (cycle == array.length) { callback(); }
		});)
	}
}

function walk(callback) {
	walker.on('file', function(path, stats, next) {
		console.log('hi') //this does not come out
		fs.readFile(path + '/' + stats.name, function(error, data) {
			doStuffWith(data);
			next();
		});
	});
}

clone(function() {
	walkDir();
});
```

**Comment by coolaj86** [comment]
That looks like code that you could make sequential:

```javascript
var dirnames = ['repo1', 'repo2'];
function doStuff(dirname) {
  var walker = walk.walk(dirname);
  // ...
  walker.on('end', function () {
    if (dirnames.length) {
      doStuff(dirnames.pop());
    } else {
      onComplete();
    }
  });
}

doStuff(dirnames.pop());

function onComplete() {
  console.log("all done");
}
```

Now that Promises have been official for a while, I ought to go back and add them to the walk module to make certain things simpler.

Also, don't use `for` loops. They're buggy and were fixed in ES5 by adding `.forEach`. You'll avoid a whole class of loop issues by using `.forEach`, which is the proper and canonical way to do a loop in JavaScript.

**Comment by BT23** [comment]
I don't think it can be sequential because the cloning function is async. The walker needs to start when all the all of the repos are done being cloned.

**Comment by coolaj86** [comment]
You can be async and sequential. Look closely at the code I provided.

**Comment by BT23** [comment]
Ah, okay. I see.

Wouldn't I need a loop anyway for doStuff(dirnames.pop()) to get all of the repos?

**Comment by coolaj86** [comment]
No, because on each completion you call the new walk and each time that walk finishes it either calls yet another new walk or it calls complete

**Comment by BT23** [comment]
Right. Absentmindedly looked over that.

**Comment by coolaj86** [comment]
Did that work out for you?

**Comment by tonedbarn** [comment]
Yes! Thanks a lot for your help.
