### ISSUE TITLE
Where are the options documented?

### ISSUE THREAD

**Issue by 0x80** [coolaj86/node-walk#44]
I'm basically trying to filter .DS_Store files, but filters: [".DS_Store"] doesn't work. Is there a way to filter this?

**Comment by coolaj86** [comment]
That should work, so I'll check into that, but every file has to be read anyway so filtering .DS_Store doesn't really change anything other than it showing up in the list, and you can just as easily ignore it yourself.

The filter is more designed to skip directories into which you don't want to descend.

**Comment by 0x80** [comment]
Ok that makes sense. And later I figured I want to filter all hidden files anyway so I'm doing this now:

```
_.remove(names, function(name){
     return name[0] === '.';
});
```
