### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ktoufique** [coolaj86/node-walk#48]
This causes a memory leak under Windows 7, 
```javascript
var walk    = require('walk');

var directory = 'H:\\';

var walker  = walk.walk(directory, { followLinks: false });

walker.on('file', function(root, stat, next) {
    
    next();
});
```

**Comment by coolaj86** [comment]
Can you explain what you mean by memory leak? What is the evidence?

Are you familiar with how V8 garbage collection works?

**Comment by coolaj86** [comment]
Further details have not been reported. Other users have not reported this. Closing.

**Comment by MatthD** [comment]
Hello,

I re-open this issue.

I used to use the module klaw which is lower than node-walk, but now for the same folder (containing millions of files & 100 000+ subfolder) I clearly have a memory issue.

From 7GB use by klaw to 18 GB used by node-walk after 1 minutes of walking directory
