### ISSUE TITLE
Stop walk

### ISSUE THREAD

**Issue by tomvlk** [coolaj86/node-walk#54]
Would it be possible to have an function to stop the current walk. For example to cancel an indexing operation. 
:rabbit: Thanks

**Comment by kurdin** [comment]
I have the same question.

**Comment by coolaj86** [comment]
Hey guys,

All you have to do is to not call `next()`.

If you're doing an indexing operation that you need to pause I would do something like this:

```javascript
var lock;
var nextNext;

var walker = walk.walk('/');

walker.on('files', function (root, files, next) {
  if (lock) {
    nextNext = next;
    return;
  }
});

function pause() {
  lock = true;
}

function resume() {
  lock = false;
  if (nextNext) { nextNext() }
}
```

**Comment by tomvlk** [comment]
Ok! Bit too easy :sweat_smile: 
Thanks for explaining it!

**Comment by kurdin** [comment]
>All you have to do is to not call next().
ok, but what if we want to call `walker.on("end", function() {});` callback in the middle execution?

**Comment by coolaj86** [comment]
Same concept:

```javascript
var lock;

var walker = walk.walk('/');

function cancel() {
  lock = true;
}

function finishHim() {
  // ...
}

walker.on('files', function (root, files, next) {
  if (lock) {
    finishHim();
    return;
  }
  // ...
});

walker.on('end', finishHim);
```
